### PR TITLE
added ncbi_tax tutorial

### PR DESCRIPTION
**Pull request by declanlim**
added tutorial markdown and related images for the NCBI taxonomy tutorial

### CODE REVIEW

**Comment by ababaian** [comment]
High level it looks good and comprehensive. Can you not delete the `toolsTemplate.md` file though please :)

**Review by ababaian — COMMENTED** [review]
undelte toolsTemplate plz

**Comment by declanlim** [comment]
sorry about that lol

**Review by ababaian — COMMENTED** [review]
Thanks :)

**Pull request merged**
