### PR TITLE
IQ Tree edits

### PR DESCRIPTION
**Pull request by caitlinoxleyhmb301**
Edited and added the files so the pictures should work.

### CODE REVIEW

**Review by ababaian — CHANGES_REQUESTED** [review]
The images are being added to `tools/img/` directory, which holds folders per tool. To prevent that directly from becoming messy could you move all your image files to `tools/img/iqtree/` and amend the markdown to the new path please.

**Comment by caitlinoxleyhmb301** [comment]
Hi prof, I deleted the files and I am trying to do one folder like everyone else did but I’m unfamiliar with git and I am not sure how to do that. I tired looking at some videos and tutorials but I am still unsure. I am sorry.Regards,Caitlin Oxley On Dec 5, 2024, at 2:01 PM, Artem Babaian ***@***.***> wrote:﻿
@ababaian requested changes on this pull request.

The images are being added to tools/img/ directory, which holds folders per tool. To prevent that directly from becoming messy could you move all your image files to tools/img/iqtree/ and amend the markdown to the new path please.

**Comment by caitlinoxleyhmb301** [comment]
Actually, I think I was able to make the correct changes.Sent from my iPhoneOn Dec 5, 2024, at 3:04 PM, Caitlin Oxley ***@***.***> wrote:﻿Hi prof, I deleted the files and I am trying to do one folder like everyone else did but I’m unfamiliar with git and I am not sure how to do that. I tired looking at some videos and tutorials but I am still unsure. I am sorry.Regards,Caitlin Oxley On Dec 5, 2024, at 2:01 PM, Artem Babaian ***@***.***> wrote:﻿
@ababaian requested changes on this pull request.

The images are being added to tools/img/ directory, which holds folders per tool. To prevent that directly from becoming messy could you move all your image files to tools/img/iqtree/ and amend the markdown to the new path please.

**Comment by ababaian** [comment]
No worries, sometimes with git it's "easier" to start again. Try forking the repo in it's current state and amending it.

**Comment by ababaian** [comment]
Re-opening as it's unresolved.

**Pull request closed without merging**
